In [11]:
# -*- coding:utf-8 -*-  
import numpy as np
#建立20个样本的二维数组
data=[[2.5,2.4]      ,[0.5,0.7]      ,[2.2,2.9]      ,[1.9,2.2]      ,[3.1,3.0]
      ,[2.3,2.7]      ,[2,1.6]      ,[1,1.1]      ,[1.5,1.6]      ,[1.1,0.9],
     [2.7,2.4]      ,[0.4,0.7]      ,[2.4,2.8]      ,[2.3,2.2]      ,[3.1,3.0]
      ,[2.4,2.4]      ,[2.2,1.7]      ,[1,1.1]      ,[1.5,1.6]      ,[3.1,1.9]]
data=np.array(data).astype(np.float) 
#1、求平均值（dataAvg）
dataAvg=np.average(data,axis=0)
print(dataAvg)

[1.96  1.945]


In [12]:
#2、求每个值与平均值的差（dataAdjust）
dataAdjust=data-dataAvg# X-avg(x)  与y-avg(y)的值
print(dataAdjust) 

[[ 0.54   0.455]
 [-1.46  -1.245]
 [ 0.24   0.955]
 [-0.06   0.255]
 [ 1.14   1.055]
 [ 0.34   0.755]
 [ 0.04  -0.345]
 [-0.96  -0.845]
 [-0.46  -0.345]
 [-0.86  -1.045]
 [ 0.74   0.455]
 [-1.56  -1.245]
 [ 0.44   0.855]
 [ 0.34   0.255]
 [ 1.14   1.055]
 [ 0.44   0.455]
 [ 0.24  -0.245]
 [-0.96  -0.845]
 [-0.46  -0.345]
 [ 1.14  -0.045]]


In [13]:
#3、求协方差矩阵
#计算任意两组数据协方差函数,
def covariance(getDataAdjust,index1,index2):
    x=getDataAdjust[:,index1:index1+1]
    y=getDataAdjust[:,index2:index2+1]
    n=x.shape[0]
    return (x*y).sum()/(n-1)
 
#计算协方差矩阵，

CovMatrix=[[covariance(dataAdjust,0,0),covariance(dataAdjust,0,1)]
           ,[covariance(dataAdjust,1,0),covariance(dataAdjust,1,1)]]
print('协方差矩阵为:')
print(CovMatrix)

协方差矩阵为:
[[0.6867368421052632, 0.5576842105263158], [0.5576842105263158, 0.5910263157894736]]


In [14]:
#4、求协方差矩阵的特征值与特征向量，如果不知道什么是特征值与特征向量，可以查查线性代数
e1,e2 = np.linalg.eig(CovMatrix)
print('------------------------')
print('协方差矩阵的特征值:')
print(e1) #[0.0490834  1.28402771] ，这里的两个值，当要降到M维（本例只能降到1维），即取最大的值，这里是1.28402771
print('------------------------')
print('协方差矩阵的特征向量:')
print(e2)

------------------------
协方差矩阵的特征值:
[1.19861527 0.07914789]
------------------------
协方差矩阵的特征向量:
[[ 0.73671449 -0.67620393]
 [ 0.67620393  0.73671449]]


In [15]:
#5、将特征值从大到小排序，选择最大的M个，取的这M个特征向量。这里只是取数，没有计算步骤
#[[-0.73517866 -0.6778734 ]     因数为上述特征值最大的取1.28402771，为第2个，所以，这里我们取每个元素数组的第2个，即e2[:,1:]
# [ 0.6778734  -0.73517866]]
#取出的值应该是[-0.6778734, -0.73517866]
 
#做矩阵乘法，将dataAdjust 乘以上述 e2[:,1:] 得出的结果即为降维后的值
finalDataX=np.matmul(dataAdjust,e2[:,1:])
print('------------------------')
print('降维后的数据:')
print(finalDataX)

------------------------
降维后的数据:
[[-0.02994503]
 [ 0.0700482 ]
 [ 0.5412734 ]
 [ 0.22843443]
 [ 0.00636131]
 [ 0.3263101 ]
 [-0.28121466]
 [ 0.02663203]
 [ 0.05688731]
 [-0.18833126]
 [-0.16518582]
 [ 0.13766859]
 [ 0.33236116]
 [-0.04204714]
 [ 0.00636131]
 [ 0.03767536]
 [-0.34278399]
 [ 0.02663203]
 [ 0.05688731]
 [-0.80402463]]
